### start simulation
POST http://localhost:8080/simulation/standalone/start
### pause simulation
POST http://localhost:8080/simulation/standalone/pause
### stop simulation
POST http://localhost:8080/simulation/standalone/stop
### simulation status
GET http://localhost:8080/simulation/standalone/status

### fetch container
GET http://localhost:8080/container/root

### fetch actors
GET http://localhost:8080/actors?container=root

### get world date
GET http://localhost:8080/simulation/standalone/time

### register actor
POST http://localhost:8080/actors/tree-03

###
