### start simulation
POST http://localhost:8080/simulation/start
### pause simulation
POST http://localhost:8080/simulation/pause
### stop simulation
POST http://localhost:8080/simulation/stop
### simulation status
GET http://localhost:8080/simulation/status

### fetch container
GET http://localhost:8080/container/root

### fetch actors
GET http://localhost:8080/actors?container=root

### get world date
GET http://localhost:8080/simulation/time

### register actor
POST http://localhost:8080/actors/120

###
