### start simulation
POST http://localhost:8080/simulation/start
### pause simulation
POST http://localhost:8080/simulation/pause
### stop simulation
POST http://localhost:8080/simulation/stop

### fetch container
GET http://localhost:8080/container/root

